name: Release Node.js app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@4.2.2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@3.10.0
    
    - name: Log in to Docker Hub
      uses: docker/login-action@3.4.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@6.15.0
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/express-app:latest